services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: acca_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: acca_dev
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports: ["6379:6379"]

volumes:
  pgdata:
